package com.dedicatedcode.reitti.service.jobs;

public enum JobType {
    GPS_IMPORT,
    GPS_INGESTION,
    GPX_IMPORT,
    GOOGLE_TIMELINE_IMPORT,
    GEOJSON_IMPORT,
    OWNTRACKS_IMPORT,
    VISIT_TRIP_DETECTION,
    SSE_EVENT,
    REVERSE_GEOCODE,
    LOCATION_PROCESSING,
    DATA_RECALCULATION,
    RECALCULATION,
    LOCATION_DATA_CLEANUP
}
